### ISSUE TITLE
error with import MetricBuilder

### ISSUE THREAD

**Issue by Qanadilo1** [bes-dev/mean_average_precision#10]
In the new update of mean_average_precision, there appears to be an error in importing.
Inside the repository **_mean_average_precision_** , there is another directory which is called **_mean_average_precision_**. Therefore when we try to import something such as 
from mean_average_precision import MetricBuilder
it gives an ImportError due to the  **_ __init.py__ _** in the main repository being empty, and it doesn't enter the second mean_average_precision directory which actually has the correct **_ __init.py__ _** file

to solve this we edited the **_ __init.py__ _** in the main repository

```console
from .mean_average_precision.metric_builder import MetricBuilder
from .mean_average_precision.mean_average_precision_2d import MeanAveragePrecision2d
from .mean_average_precision.multiprocessing import MetricMultiprocessing
```

**Comment by bonastreyair** [comment]
Just to reference the existing PR #12

**Comment by bes-dev** [comment]
Thanks for your contribution!
PR was merged
