### ISSUE TITLE
considering new pip release version

### ISSUE THREAD

**Issue by bonastreyair** [bes-dev/mean_average_precision#13]
Installing via pip version 0.0.2.1 does not contain latests useful changes:
 - Multiprocessing 
 - MetricBuilder

Have you ever considered to release a new version to pip? Is it stable enough?

---
Other questions:
- Have you ever considered following [Semanting Versioning](https://semver.org/)? 
- Have you ever considered adding a `CHANGELOG.md` to your repo?

---
I like this repo a lot! Thanks! :+1:

**Comment by bes-dev** [comment]
Hi,

Thanks for your feedback. Unfortunately, I don't have enoght time to develop this project as quickly as I would like. But yes, I have plans to update pypi package. Thanks for good idea about CHANGELOG.md, I'll add it in next versions. What about versioning, I planned switch to calendar versioning system.

**Comment by bonastreyair** [comment]
Awesome! Glad this project is still active! Thanks for your quick response!

Can't wait for those changes, then!

Thanks again :+1: !!

**Comment by mohit138** [comment]
> Installing via pip version 0.0.2.1 does not contain latests useful changes:
> 
> * Multiprocessing
> * MetricBuilder
> 
> Have you ever considered to release a new version to pip? Is it stable enough?
> 
> Other questions:
> 
> * Have you ever considered following [Semanting Versioning](https://semver.org/)?
> * Have you ever considered adding a `CHANGELOG.md` to your repo?
> 
> I like this repo a lot! Thanks! 👍

I copied everything as it is, in README, still, I am having an error- 
"ImportError: cannot import name 'MetricBuilder' from 'mean_average_precision' (/opt/conda/lib/python3.7/site-packages/mean_average_precision/__init__.py)"

Can you please help me out in this?
I feel it might be somewhat related to this issue raised.
It would really help me out, if someone could clear this out to me,
Thank you

**Comment by bonastreyair** [comment]
`MetricBuilder` is just available on the master and development branches.

If you are using the `0.0.2.1` pip version you must use `MetricAveragePrecision` class instead of `MetricBuilder` 

You can always check the `REAMDE.md` from the exact commit of `0.0.2.1` - https://github.com/bes-dev/mean_average_precision/tree/80d888830989fef839643e67f5075fb2a15f1f1c

**Comment by mohit138** [comment]
> `MetricBuilder` is just available on the master and development branches.
> 
> If you are using the `0.0.2.1` pip version you must use `MetricAveragePrecision` class instead of `MetricBuilder`
> 
> You can always check the `REAMDE.md` from the exact commit of `0.0.2.1` - https://github.com/bes-dev/mean_average_precision/tree/80d888830989fef839643e67f5075fb2a15f1f1c

Oookay. Thanks a lot. 
Also, thank you for replying so quickly.

**Comment by bes-dev** [comment]
@bonastreyair @mohit138 Good news. I found a little bit free time for this project, and the new version of mean_average_precision library was released. Moreover, now the latest version is available from PyPi package.
