### ISSUE TITLE
Changed previous 0.0.2.1 release using pip

### ISSUE THREAD

**Issue by bonastreyair** [bes-dev/mean_average_precision#14]
After the latests pip release, if I want to install previous version using `pip install mean-average-precision==0.0.2.1` it throws an error.

It tells that `MeanAveragePrecision` does not longer exists. To solve it I have to use `MeanAveragePrecision2d` which is from the next release `2021.4.23.0` which is kind of weird... Checking for `0.0.2.1` release in GitHub I don't understand what's going on...

```python
>>> from mean_average_precision import MeanAveragePrecision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MeanAveragePrecision' from 'mean_average_precision'
```

When installing previous version, release `0.0.2.1` weights `14KB`
```bash
>> pip install mean-average-precision==0.0.2.1
Collecting mean-average-precision==0.0.2.1
  Downloading mean_average_precision-0.0.2.1-py3-none-any.whl (14 kB)
```
... and when installing the latest release `2021.4.23.0`, it also weights the same `14KB`
```bash
>> pip install mean-average-precision==2021.4.23.0
Collecting mean-average-precision==2021.4.23.0
  Downloading mean_average_precision-2021.4.23.0-py3-none-any.whl (14 kB)
```
With both versions I can do:
```python
from mean_average_precision import MetricBuilder
```
...which should only be available on the latest release.

Could it be that you re-uploaded the `0.0.2.1` release with the latest code by mistake? (I didn't knew that was even possible in pip...)
Be aware that if that's the case people that were stitching to the `0.0.2.1` version will now have broken workflows like it happened to me...

**Comment by bes-dev** [comment]
Hey,

1) `from mean_average_precision import MetricBuilder` is incorrect, let's try to use `from mean_average_precision import MetricBuilder`
2) Let's try to latest version 2021.4.26.0

**Comment by bonastreyair** [comment]
Thanks for your response. 

1. I don't see the difference, what's exactly incorrect? (I had a plural typo, if that's what you refer to, fixed in the comment :) )
2. What's new on `2021.4.26.0`?

**Comment by bes-dev** [comment]
1. `Metric(s)Builder` is incorrect, should be `MetricBuilder`
2. I checked 2021.4.26.0 by hands and it works for me, for 2021.4.23.0 was only automaticaly checks and it may be broken.

**Comment by bonastreyair** [comment]
OK. Thanks!

Although this issue refers to release `0.0.2.1` that no longer works as it worked before. Can you check how this error appears?

**Comment by bes-dev** [comment]
@bonastreyair it's so strange, I think that it is an error on pypi.org side. History of releases for mean_average_precision looks ok: https://pypi.org/project/mean-average-precision/#history

**Comment by bonastreyair** [comment]
really weird, when you do `pip install mean-average-precision==0.0.2.1` it actually installs the version with `MetricBuilder`
