### ISSUE TITLE
Difficult and Crowd

### ISSUE THREAD

**Issue by 2113vm** [bes-dev/mean_average_precision#16]
Thanks for the great implementation!

Could you, please, explain to me what "difficult" and "crowd" mean and how I can create them if I have only coordinates and labels?

**Comment by 2113vm** [comment]
I really didn't find anything about that, sorry for google like question

**Comment by bes-dev** [comment]
@2113vm "crowd" (few objects annotated with single bbox) and "difficult" (hard to detect objects do not contribute to metric) defined as in VOC PASCAL and COCO annotation. If you don't want to use it, just set it by '0'.

**Comment by 2113vm** [comment]
Thank you for the answer!
