### ISSUE TITLE
problem in num_classes greater than 1

### ISSUE THREAD

**Issue by ck-amrahd** [bes-dev/mean_average_precision#2]
import numpy as np
    from mean_average_precision import MeanAveragePrecision

    gt1 = np.array([
        [439, 157, 556, 241, 0, 0, 0]
    ])

    pred1 = np.array([
        [429, 219, 528, 247, 0, 0.46]
    ])

    gt2 = np.array([
        [437, 155, 562, 237, 1, 0, 0]
    ])

    pred2 = np.array([
        [425, 215, 529, 249, 0, 0.46]
    ])

    metric_fn = MeanAveragePrecision(num_classes=2)

    metric_fn.add(pred1, gt1)
    metric_fn.add(pred2, gt2)

    print('pascal voc 11 points ap:')
    print(metric_fn.value(iou_thresholds=0.5)['mAP'])

**Comment by bes-dev** [comment]
Hey,

Thanks for feedback! Currently, you can use hotfix from this branch: https://github.com/bes-dev/mean_average_precision/tree/sb/issue_2
It will be merged to master soon

Best regards
